RECID_DICT = {'affiliations': [[1,
                   '',
                   'Cologne U.',
                   '',
                   'Universit\xc3\xa4t zu K\xc3\xb6ln, Fachgruppe Physik, c/o I.Physikalisches Institut, Z\xc3\xbclpicher Stra\xc3\x9fe 77, 50937 K\xc3\xb6ln, Germany',
                   ['http://www.physik.uni-koeln.de/'],
                   True,
                   'Cologne U.'],
                  [2,
                   '',
                   'Julich, Forschungszentrum',
                   '',
                   'Forschungszentrum (FZ) J\xc3\xbclich GmbH, Institut f\xc3\xbcr Kernphysik (IKP), Wilhelm-Johnen-Stra\xc3\x9fe, Germany',
                   ['http://www.fz-juelich.de/ikp/'],
                   True,
                   'Julich, Forschungszentrum'],
                  [3,
                   '',
                   'Fermilab',
                   '',
                   'Fermi National Accelerator Laboratory (FNAL), P.O. Box 500, Batavia, IL 60510-0500, USA',
                   ['http://www.fnal.gov/',
                    'https://twitter.com/Fermilab',
                    'https://www.youtube.com/user/fermilab'],
                   True,
                   'Fermilab']],
 'authors': [[1,
              '',
              'Zurek',
              'Maria',
              'Zurek, Maria',
              '',
              [['Julich, Forschungszentrum', 'Affiliated with'],
               ['Cologne U.', 'Affiliated with']],
              [['INSPIRE-00269753', 'Inspire ID']]],
             [2,
              '',
              'Albrow',
              'Michael',
              'Albrow, Michael',
              '',
              [['Fermilab', 'Affiliated with']],
              [['', 'Inspire ID']]]],
 'collaboration': ['CDF'],
 'experiment_number': ['FNAL-E-0830'],
 'last_modified': 1533832154,
 'paper_id': '1',
 'paper_title': 'Central Exclusive $\\pi^{+}\\pi^{-}$ Production in $p\\bar{p}$ Collisions at $\\sqrt{s} = 0.9$ and 1.96 TeV at the Tevatron',
 'reference_ids': []}

