JOURNAL_DICT = {
    'Acta.':'Acta Astron.',
    'Adv.Space.':'Adv.Space Res.',
    'AIP.':'AIP Conf.Proc.',
    'Annales':'Annales Henri Poincare',
    'Annals':'Annals Phys.',
    'ASP.':'ASP Conf.Ser.',
    'ASSL':'Astrophys.Space Sci.Libr.',
    'Astron.Nachr.':'Astron.Nachr.',
    'Astroph.J.':'Astrophys.J.',
    'Astrophys.Space.':'Astrophys.Space Sci.',
    'Baltic.':'Baltic Astron.',
    'Comm.Math.Phys.':'Commun.Math.Phys.',
    'Commun.Nonlinear.':'Commun.Nonlinear Sci.Numer.Simul.',
    'Contrib.Astron.Obs.Skalnate.':'Contrib.Astron.Obs.Skalnate Pleso',
    'EAS.Pub.Ser.':'EAS Publ.Ser.',
    'ESA.':'ESA Spec.Publ.',
    'Geophys.Astrophys.Fluid.':'Geophys.Astrophys.Fluid Dynamics',
    'Gravitat.Cosmol.':'Grav.Cosmol.',
    'IAU.':'IAU Symp.',
    'J.Fluid.':'J.Fluid Mech.',
    'J.Nonlin.Mathematical':'J.Nonlin.Mathematical Phys.',
    'Lect.Notes.':'Lect.Notes Phys.',
    'Low.':'Low Temp.Phys.',
    'New.':'New J.Phys.',
    'Phys.Rev.L.':'Phys.Rev.Lett.',
    'Proc.SPIE.':'Proc.SPIE Int.Soc.Opt.Eng.',
    'Res.Astron.Astroph.':'Res.Astron.Astrophys.',
    'Sov.Phys.JETP.Lett.':'JETP Lett.',
}

BIBCODE_DICT = {
    'A&A':'Astron.Astrophys.',
    'A&ARv':'Astron.Astrophys.Rev.',
    'A&AS':'Astron.Astrophys.Suppl.Ser.',
    'A&AT':'Astron.Astrophys.Trans.',
    'A&G':'Astron.Geophys.',
    'AAS':'Amer.Astron.Soc.Meeting',
    'AcA':'Acta Astron.',
    'AcAau':'Acta Astronaut.',
    'AcApS':'Acta Astrophys.Sin.',
    'AcASn':'Acta Astron.Sin.',
    'AcC':'Acta Cosmologica',
    'AcEle':'Acta Electron.',
    'AcHPh':'Helv.Phys.Acta',
    'AcMec':'Acta Mech.',
    'AcMet':'Acta Metall.',
    'AcNum':'Acta Numer.',
    'AcOpt':'Opt.Acta',
    'AcPhA':'Acta Phys.Austriaca',
    'AcPhH':'Acta Phys.Hung.',
    'AcPP':'Acta Phys.Polon.',
    'AcPPA':'Acta Phys.Polon.::A',
    'AcPPB':'Acta Phys.Polon.::B',     
    'AcPSl':'Acta Phys.Slov.',
    'AcPSn':'Acta Phys.Sin.',
    'AcRhe':'Rheologica Acta',
    'ACSJ':'J.Amer.Ceramic Soc.',
    'AcSpe':'Spectrochim.Acta A',
    'AdA&A':'Adv.Astron.Astrophys.',
    'AdApM':'Adv.Appl.Math.',
    'ADNDT':'Atom.Data Nucl.Data Tabl.',
    'AdPhy':'Adv.Phys.',
    'AdSpR':'Adv.Space Res.',
    'AeJ':'J.Aeron.Sci.',
    'AExpr':'Astron.Express',
    'Afz':'Astrofiz.',
    'AIAAJ':'AIAA J.',
    'AIChE':'Aiche J.',
    'AIPC':'AIP Conf.Proc.',
    'AJ':'Astron.J.',
    'AJSE':'Arabian J.Sci.Eng.',
    'AmJPh':'Am.J.Phys.',
    'AmJS':'Am.J.Sci.',
    'AmMin':'Amer.Miner.',
    'AmSci':'Am.Sci.',
    'AN':'Astron.Nachr.',
    'AnaCh':'Anal.Chem.',
    'AnAp':'Annales Astrophys.',
    'AnGeo':'Ann.Geophys.',
    'AnIHP':'Ann.Inst.Henri Poincare Phys.Theor.',    
    'AnIPS':'Annals Israel Phys.Soc.',
    'AnP':'Annalen Phys.',
    'AnPh':'Annales Phys.(France)',
    'AnPhy':'Annals Phys.',
    'AnRFM':'Ann.Rev.Fluid Mech.',
    'Ap':'Astrophysics',
    'Ap&SS':'Astrophys.Space Sci.',
    'ApEnM':'Appl.Envir.Microbiol.',
    'APh':'Astropart.Phys.',
    'ApJ':'Astrophys.J.',
    'ApJS':'Astrophys.J.Suppl.',
    'ApL':'Astrophys.Lett.',
    'ApL&C':'Astrophys.Lett.Commun.',
    'ApMaL':'Appl.Math.Lett.',
    'ApMaO':'Appl.Math.Optim.',
    'ApMM':'Appl.Math.Mech.',
    'ApMRv':'Appl.Mech.Rev.',
    'ApNM':'Appl.Numer.Math.',
    'ApNr':'Astrophys.Nor.',
    'ApOpt':'Appl.Opt.',
    'AppAn':'Appl.Anal.',
    'ApPhB':'Appl.Phys.B, Lasers Opt.',
    'ApPhL':'Appl.Phys.Lett.',
    'ApPhy':'Appl.Phys.',
    'ApPPL':'Appl.Phys.B Photophys.Laser Chem.',
    'ApScR':'Appl.Sci.Res.',
    'ApSpe':'Appl.Spectrosc.',
    'ApSS':'Appl.Surf.Sci.',
    'ApSup':'IEEE Trans.Appl.Supercond.',
    'ArA':'Ark.Mat.Astron.Fys.',
    'ARA&A':'Ann.Rev.Astron.Astrophys.',
    'ArApM':'Arch.Appl.Mech.',
    'ARep':'Astron.Rep.',
    'AREPS':'Ann.Rev.Earth Planet.Sci.',
    'arnps':'Ann.Rev.Nucl.Part.Sci.',
    'ArRMA':'Arch.Ration.Mech.Anal.',
    'ASAJ':'J.Acoust.Soc.Am.',
    'ASPC':'ASP Conf.Ser.',
    'AstBu':'Astrophys.Bull.',
    'AstL':'Astron.Lett.',
    'AtERv':'At.Energy Rev.',
    'ATJFE':'J.Fluids Eng.',
    'AtO':'Atmos. Ocean Opt.',
    'AuJPh':'Austral.J.Phys.',
    'AuMSJ':'J.Austral.Math.Soc.Ser.B',
    'Autom':'Automatica',
    'AZh':'Astron.Zh.',
    'BAAA':'Bol.A.A.Astron.',
    'BaltA':'Baltic Astron.',
    'BASI':'Bull.Astron.Soc.India',
    'BlJPh':'Bulg.J.Phys.',
    'BrJPh':'Braz.J.Phys.',
    'BSAO':'Bull.Spec.Astrophys.Obs.N.Caucasus',
    'BSRSL':'Bull.Soc.Roy.Sci.Liege',
    'CAD':'Comput. Aided Geom. Des.',
    'CaJCh':'Can.J.Chem.',
    'CaJPh':'Can.J.Phys.',
    'CEJPh':'Central Eur.J.Phys.',
    'CeMDA':'Celestial Mech.',
    'CGIP':'Comput.Vision Graphics Image Proc.',
    'ChA&A':'Chin.Astron.Astrophys.',
    'Chaos':'Chaos',
    'ChEnS':'Chem.Eng.Sci.',
    'ChGeo':'Chem. Geol.',
    'ChJAA':'Chin.J.Astron.Astrophys.',
    'ChJNP':'Chin.J.Nucl.Phys.',
    'ChJPh':'Chin.J.Phys.',
    'ChPhy':'Chin.Phys.',
    'ChPhB':'Chin.Phys.::B',
    'ChPhC':'Chin.Phys.::C',
    'ChPhL':'Chin.Phys.Lett.',
    'CJLTP':'Chin.J.Low Temp.Phys.',
    'CMAME':'Comput.Methods Appl.Mech.Eng.',
    'CMaPh':'Commun.Math.Phys.',
    'CMT':'Contin.Mech.Thermodyn.',
    'CMwA':'Comput.Math.Appl.',
    'CoFl':'Combust.Flame',
    'ComAp':'Comments Astrophys.',
    'ComMP':'Comments Mod.Phys.',
    'Comp':'Computer',
    'ComPh':'Comput.Phys.',
    'ConPh':'Contemp.Phys.',
    'CoPhC':'Comput.Phys.Commun.',
    'CoPP':'Comments Plasma Phys.Contr.Fusion',
    'CPAM':'Commun.Pure Appl.Math.',
    'CPL':'Chem.Phys.Lett.',
    'CQGra':'Class.Quant.Grav.',
    'CRAS':'C.R.Acad.Sci.',
    'CRASB':'C.R.Acad.Sci.::B',
    'CRASP':'C.R.Acad.Sci.IV Phys.Astrophys.',
    'CRPhy':'Comptes Rendus Physique',
    'Cryo':'Cryogenics',
    'CryRp':'Cystallogr.Rep.',
    'CSF':'Chaos Solitons Fractals',
    'CST':'Combust.Sci.Tech.',
    'CzJPh':'Czech.J.Phys.',
    'CzMJ':'Czech.Math.J.',
    'Disc':'Discover',
    'DokPh':'Phys.Dokl.',
    'DynCo':'J.Guid.Control Dyn.',
    'E&PSL':'Earth Planet.Sci.Lett.',
    'EcSJ':'J.Electrochem.Soc.',
    'EJPh':'Eur.J.Phys.',
    'EJTP':'Electron.J.Theor.Phys.',
    'EL':'Europhys.Lett.',
    'Elek':'Radiotekh.Elektron.',
    'ElL':'Electron.Lett.',
    'ElP':'Electron.Power',
    'EM&P':'Earth Moon Planets',
    'Endvr':'Endeavour',
    'EnST':'Environ.Sci.Tech.',
    'Entrp':'Entropy',
    'EPJA':'Eur.Phys.J.::A',
    'EPJAP':'Eur.Phys.J.Appl.Phys.',
    'EPJB':'Eur.Phys.J.::B',
    'EPJC':'Eur.Phys.J.::C',
    'EPJD':'Eur.Phys.J.::D',
    'EPJE':'Eur.Phys.J.::E',
    'EPJH':'Eur.Phys.J.::H',
    'EPJP':'Eur.Phys.J.Plus',
    'EPJST':'Eur.Phys.J.ST',
    'EPJWC':'EPJ Web Conf.',
    'ESAJ':'ESA J.',
    'ExA':'Exper.Astron.',
    'ExT':'Instrum.Exp.Tech.',
    'FAAp':'Funct.Anal.Appl.',
    'FBS':'Few Body Syst.',
    'FCPh':'Fund.Cosmic Phys.',
    'Fiz':'Fizika',
    'FizA':'Fizika::A',
    'FizB':'Fizika::B',
    'FizMS':'Fiz.Mnogochast.Sistem',
    'FizTT':'Fiz.Tverd.Tela',
    'FlDy':'Fluid Dynamics',
    'FlDyR':'Fluid Dynamics Res.',
    'FlMSR':'Fluid Mech.Sov.Res.',
    'FoPh':'Found.Phys.',
    'ForPh':'Fortsch.Phys.',
    'GApFD':'Geophys.Astrophys.Fluid Dynamics',
    'GeCoA':'Geochim.Cosmochim.Acta',
    'GeGe':'Stud.Geophys.Geod.',
    'GeoJ':'Geophys.J.(U.S.)',
    'GeoJI':'Geophys.J.Int.',
    'GeoRL':'Geophys.Res.Lett.',
    'GrCo':'Grav.Cosmol.',
    'GReGr':'Gen.Rel.Grav.',
    'HDP':'Handb.Phys.',
    'HeaPh':'Health Phys.',
    'HiA':'Highlights Astron.',
    'HMT':'Int.J.Heat Mass Transf.',
    'HTHP':'High Temp.High Pressures',
    'HyInt':'Hyperfine Interact.',      
    'IAUC':'IAU Circ.',
    'IAUS':'IAU Symp.',
    'Icar':'Icarus',
    'IComM':'IEEE Commun.Mag.',
    'ICRC':'ICRC',
    'ICSE':'Impact Comput.Sci.Eng.',
    'IDAQP':'Inf.Dim.Anal.Quant.Probab.Rel.Top.',
    'IER':'Int.Elek.Rundsch.',
    'IJBC':'Int.J.Bifurc.Chaos',
    'IJC':'Int.J.Control',
    'IJE':'Int.J.Electron.',
    'IJES':'Int.J.Eng.Sci.',
    'IJIMW':'Int.J.Infrared MM Waves',
    'IJMPA':'Int.J.Mod.Phys.::A',
    'IJMPB':'Int.J.Mod.Phys.::B',
    'IJMPC':'Int.J.Mod.Phys.::C',
    'IJMPD':'Int.J.Mod.Phys.::D',
    'IJMPE':'Int.J.Mod.Phys.::E',    
    'IJMPS':'Int.J.Mod.Phys.Conf.Ser.',
    'IJMSI':'Int.J.Mass Spectr.Ion Process.',
    'IJMSp':'Int.J.Mass Spectrometry',
    'IJNA':'IMA J.Numer.Anal.',
    'IJNME':'Int.J.Numer.Meth.Eng.',
    'IJNMF':'Int. J. Numer. Methods Fluids',
    'IJPAM':'Indian J.Pure Appl.Math.',
    'IJPAP':'Indian J.Pure Appl.Phys.',
    'IJQC':'Int.J.Quant.Chem.',
    'IJQE':'IEEE J.Quant.Electron.',
    'IJRA':'IEEE J.Robot.Automat.',
    'IJScA':'Int.J.Supercomput.Appl.',
    'IJSSC':'IEEE J.Solid State Circuits',
    'IJTP':'Int.J.Theor.Phys.',
    'InCh':'Inorg.Chem.',
    'InfCo':'Info.Control',
    'InfPh':'Infrared Physics',
    'InJPh':'Indian J.Phys.',
    'InJPA':'Indian J.Phys.::A',
    'InJPB':'Indian J.Phys.::B',
    'InJTP':'Indian J.Theor.Phys.',
    'InPhT':'Infrared Phys.Tech.',
    'InvPr':'Inverse Prob.',
    'IPTL':'IEEE Photonics Tech.Lett.',
    'IrAJ':'Irish Astron.J.',
    'IST':'Issues Sci.Technol.',
    'ISTSP':'IEEE J.Sel.Top.Sig.Proc.',
    'ITAC':'IEEE Trans.Automatic Control',
    'ITASS':'IEEE Trans.Acoust.Speech Signal Proc.',
    'ITBE':'IEEE Trans.Biomed.Eng.',
    'ITCmp':'IEEE Trans.Comput.',
    'ITCom':'IEEE Trans.Commun.',
    'ITCS':'IEEE Trans.Circuits Theor.',
    'ITEdu':'IEEE Trans.Educ.',
    'ITEI':'IEEE Trans.Electric.Insul.',
    'ITElC':'IEEE Trans.Electromagn.Compat.',
    'ITGRS':'IEEE Trans.Geosci.Remote Sensing',
    'ITIA':'IEEE Trans.Indust.Appl.',
    'ITIM':'IEEE Trans.Instrum.Measur.',
    'ITIT':'IEEE Trans.Info.Theor.',
    'ITM':'IEEE Trans.Magnetics',
    'ITMTT':'IEEE Trans.Microwave Theor.Tech.',
    'ITNN':'IEEE Trans.Neural Networks',
    'ITNS':'IEEE Trans.Nucl.Sci.',
    'ITPAM':'IEEE Trans.Pattern Anal.Machine Intell.',
    'ITPS':'IEEE Trans.Plasma Sci.',
    'ITRA':'IEEE Trans.Robotics Automation',
    'ITSE':'IEEE Trans.Software Eng.',
    'ITSMC':'IEEE Trans.Syst.Man Cybern.',
    'ITSP':'IEEE Trans.Signal Process.',
    'ITUFF':'IEEE Trans.Ultrason.Ferroelectr.Freq.Control',
    'IzMat':'Izv.Math.',
    'JAChS':'J.Am.Chem.Soc.',
    'JAerS':'J.Aerosol Sci.',
    'JaJAP':'Jap.J.Appl.Phys.',
    'JAllC':'J.Alloys Compounds',
    'JAnSc':'J.Astronaut.Sci.',
    'JAP':'J.Appl.Phys.',
    'JApA':'J.Astrophys.Astron.',
    'JAPh':'J.Appl.Physiol.',
    'JApMa':'Ima J.Appl.Math.',
    'JApMe':'J.Appl.Meteor.',
    'JAtC':'J.Atmos.Chem.',
    'JATP':'J.Atmos.Terr.Phys.',
    'JAtS':'J.Atmos.Sci.',
    'JAVSO':'J.Am.Assoc.Var.Star Obs.',
    'JBAA':'J.Br.Astron.Assoc.',
    'JBIS':'J.Br.Interplanet.Soc.',
    'JCh':'J.Chromatogr.',
    'JChPh':'J.Chem.Phys.',
    'JCIS':'J.Coll.Interface Sci.',
    'JCM':'J.Comput.Appl.Math.',
    'JCoCh':'J.Comput.Chem.',
    'JCoPh':'J.Comput.Phys.',
    'JCrGr':'J.Cryst.Growth',
    'JDE':'J.Diff.Eq.',
    'JEEEA':'J.Electr.Electron.Eng.Aust.',
    'JEMat':'J.Electron.Mater.',
    'JESRP':'J.Electron Spectrosc.Rel.Phenom.',
    'JETP':'J.Exp.Theor.Phys.',
    'JETPL':'JETP Lett.',
    'JEWA':'J.Electromagn.Waves Appl.',
    'JFM':'J.Fluid Mech.',
    'JG':'J.Geology',
    'JGG':'J.Geomag.Geoelectr.Japan',
    'JGla':'J.Glaciol.',
    'JGP':'J.Geom.Phys.',
    'JGR':'J.Geophys.Res.',
    'JHA':'J.Hist.Astron.',
    'JHEP':'JHEP',
    'JHyd':'J.Hydronaut.',
    'JIEq':'J.Integ.Eq.',
    'JIMIA':'J.Inst.Math.Appl.',
    'jimo':'WGN',
    'JKAS':'J.Korean Astron.Soc.',
    'JKPS':'J.Korean Phys.Soc.',
    'JLCM':'J.Less Common Met.',
    'JLTP':'J.Low.Temp.Phys.',
    'JLwT':'J.Lightwave Tech.',
    'JMAA':'J.Math.Anal.Appl.',
    'JMagR':'J.Magn.Resonance',
    'JMatR':'J.Mater.Res.',
    'JMatS':'J.Materials Sci.Lett.',
    'JMec':'J.Mecan.',
    'JMecA':'J.Meca.Theor.Appl.',
    'JMemS':'J.Microelectromech.Syst.',
    'JMet':'J.Metals',
    'JMMM':'J.Magn.Magn.Mater.',
    'JMoEl':'J.Molec.Electron.',
    'JMolE':'J.Molec.Evol.',
    'JMOp':'J.Mod.Opt.',
    'JMoSp':'J.Molec.Spectrosc.',
    'JMoSt':'J.Molec.Struc.',
    'JMP':'J.Math.Phys.',
    'JMPSo':'J.Mech.Phys.Solids',
    'JNCS':'J.Noncryst.Solids',
    'JNET':'J.Nonequil.Thermo.',
    'JNMP':'J.Nonlin.Mathematical Phys.',
    'JNOPM':'J.Nonlin.Opt.Phys.Mater.',
    'JNS':'J.Nonlin.Sci.',
    'JNuM':'J.Nucl.Mater.',
    'JOpt':'J.Optics',
    'JOptA':'J.Opt.',
    'JOptB':'J.Opt.B Quant.Semiclass.Opt.',
    'JOSAA':'J.Opt.Soc.Am.',
    'JOTA':'J.Optim.Th.Appl.',
    'JPCM':'J.Phys.Condens.Matter',
    'JPCRD':'J.Phys.Chem.Ref.Data',
    'JPCS':'J.Phys.Chem.Solids',
    'JPDC':'J.Parallel Distrib.Comput.',
    'JPhA':'J.Phys.::A',
    'JPhB':'J.Phys.::B',
    'JPhC':'J.Phys.::C',
    'JPhCh':'J.Phys.Chem.',
    'JPhD':'J.Phys.::D',
    'JPhE':'J.Phys.::E',
    'JPhF':'J.Phys.::F',
    'JPhG':'J.Phys.::G',
    'JPhSt':'J.Phys.Stud.',
    'JPhys':'J.Phys.(France)',
    'JPlPh':'J.Plasma Phys.',
    'JPO':'J.Phys.Oceanogr.',
    'JPP':'J.Propulsion Power',
    'JQSRT':'J.Quant.Spectrosc.Radiat.Trans.',
    'JRAC':'J.Radioanal.Chem.',
    'JRASC':'J.Roy.Astron.Soc.Canada',
    'JRNBS':'J.Res.Natl.Bur.Stand.',
    'JSCom':'J.Sci.Comput.',
    'JSLR':'J.Russ.Laser Res.',
    'JSMTE':'J.Stat.Mech.',
    'JSP':'J.Statist.Phys.',
    'JSup':'J.Supercond.',
    'JSV':'J.Sound Vibrat.',
    'JVST':'J.Vac.Sci.Tech.',
    'JWasA':'J.Wash.Acad.Sci.',
    'KFNT':'Kinematika Fiz.Nebesnykh Tel',
    'LaPhy':'Laser Phys.',
    'LicOB':'Lick Obs.Bull.',
    'LiCr':'Mol.Cryst.Liq.Cryst.',
    'LMaPh':'Lett.Math.Phys.',
    'LNP':'Lect.Notes Phys.',
    'LPB':'Laser Part.Beams',
    'LRR':'Living Rev.Rel.',
    'LRSP':'Living Rev.Sol.Phys.',
    'M&P':'Moon Planets',
    'MaCom':'Math.Comput.',
    'Math':'Mathematika',
    'MatL':'Mater.Lett.',
    'MComM':'Math.Comput.Modelling',
    'Mecc':'Meccanica',
    'MedPh':'Med.Phys.',
    'MeReC':'Mech.Res.Commun.',
    'Metic':'Meteoritics',
    'Metro':'Metrologia',
    'MiOTL':'Microw.Opt.Technol.Lett.',
    'MmARB':'Acad.Roy.Belg.Sci.Mem.',
    'MMAS':'Math.Methods Appl.Sci.',
    'MmRAS':'Mem.Roy.Astron.Soc.',
    'MmSAI':'Mem.Soc.Ast.It.',
    'MNRAS':'Mon.Not.Roy.Astron.Soc.',
    'MolPh':'Mol.Phys.',
    'ModPh':'Mod.Phys.',
    'MPLA':'Mod.Phys.Lett.::A',
    'MPLB':'Mod.Phys.Lett.::B',
    'MSEng':'Mater.Sci.Eng.',
    'MSRSL':'Mem.Soc.Roy.Sci.Liege',
    'MWRv':'Mon.Weather Rev.',
    'NanoL':'Nano Lett.',
    'Nanot':'Nanotechnol.',
    'Natur':'Nature',
    'NatPh':'Nature Phys.',
    'NCimA':'Nuovo Cim.::A',
    'NCimB':'Nuovo Cim.::B',
    'NCimC':'Nuovo Cim.::C',
    'NCimD':'Nuovo Cim.::D',
    'NCimL':'Lett.Nuovo Cim.',
    'NCimR':'Riv.Nuovo Cim.',    
    'NDS':'Nucl.Data Sheets',
    'NewA':'New Astron.',
    'NewAR':'New Astron.Rev.',
    'NewSc':'New Sci.',
    'NIMPA':'Nucl.Instrum.Meth.::A',
    'NIMPB':'Nucl.Instrum.Meth.::B',
    'NIMPR':'Nucl.Instrum.Meth.',
    'NInfo':'Nauchnye Inform.Astron.Sov.Akad Nauk SSR',
    'NISTJ':'J.Res.Natl.Inst.Stand.Tech.',
    'NJPh':'New J.Phys.',
    'Nonli':'Nonlinearity',
    'NPGeo':'Nonlin.Proc.Geophys.',
    'NPhS':'Nature Phys.Sci.',
    'NucFu':'Nucl.Fusion',
    'NucIM':'Nucl.Instrum.Meth.',
    'NucPh':'Nucl.Phys.',
    'NuMat':'Numer.Math.',
    'NuPh':'Nucl.Phys.',
    'NuPhA':'Nucl.Phys.::A',
    'NuPhB':'Nucl.Phys.::B',
    'NuPhS':'Nucl.Phys.Proc.Suppl.',
    'NW':'Naturwiss.',
    'NYASA':'Annals N.Y.Acad.Sci.',
    'Obs':'Observatory',
    'OLEB':'Orig.Life.Evol.Biosph.',
    'OptCo':'Opt.Commun.',
    'OptEn':'Opt.Eng.',
    'OptL':'Opt.Lett.',
    'OptLT':'Opt.Laser Tech.',
    'OptMa':'Opt.Mater.',
    'OptN':'Optics News',
    'OptPN':'Opt.Phontonics News',
    'OptQE':'Opt.Quant.Electron.',
    'OSAJ':'J.Opt.Soc.Am.',
    'P&SS':'Planet.Space Sci.',
    'PADEU':'Publ.Astron.Dep.Eotvos Univ.',
    'PAN':'Phys.Atom.Nucl.',
    'ParC':'Parallel Comput.',
    'PaReL':'Pattern Recog.Lett.',
    'PASA':'Publ.Astron.Soc.Austral.',
    'PASAu':'Proc.Astron.Soc.Austral.',
    'PASJ':'Publ.Astron.Soc.Jap.',
    'PASP':'Publ.Astron.Soc.Pac.',
    'PDO':'Publ.Dominion Astrophys.Obs.',
    'PEPI':'Phys.Earth Planet.Interiors',
    'PhB':'Phys.Bull.',
    'PhFl':'Phys.Fluids',
    'PhL':'Phys.Lett.',
    'PhLA':'Phys.Lett.::A',
    'PhLB':'Phys.Lett.::B',
    'PhLC':'Phys.Rept.',
    'PhoSp':'Photonics Spectra',
    'PhP':'Phys.Perspect.',
    'PhPl':'Phys.Plasmas',
    'PhR':'Phys.Rept.',
    'PhRv':'Phys.Rev.',
    'PhRvA':'Phys.Rev.::A',
    'PhRvB':'Phys.Rev.::B',
    'PhRvC':'Phys.Rev.::C',
    'PhRvD':'Phys.Rev.::D',
    'PhRvE':'Phys.Rev.::A',
    'PhRvL':'Phys.Rev.Lett.',
    'PhRvS':'Phys.Rev.ST Accel.Beams',
    'PhT':'Phys.Today',
    'PhTea':'Phys.Teacher',
    'Phy':'Physica',
    'PhyA':'Physica::A',
    'PhyB':'Physica::B',
    'PhyC':'Physica::C',
    'PhyD':'Physica::D',
    'PhyEd':'Phys.Educ.India',
    'PhST':'Phys.Scripta::T',
    'PhyS':'Phys.Scripta',
    'PlPh':'Plasma Phys.',
    'PlPhR':'Plasma Phys.Rep.',
    'PMag':'Phil.Mag.',
    'PMagA':'Phil.Mag.::A',
    'PMagB':'Phil.Mag.::B',
    'PMagL':'Phil.Mag.Lett.',
    'PMB':'Phys.Med.Biol.',
    'PNAS':'Proc.Nat.Acad.Sci.',
    'PPCF':'Comments Plasma Phys.Contr.Fusion',
    'PPN':'Phys.Part.Nucl.',
    'PQE':'Prog.Quant.Electron.',
    'Prama':'Pramana',
    'PrECS':'Prog.Energy Combust.Sci.',
    'PreR':'Precambrian Res.',
    'PRI':'Phys.Res.Int.',
    'PriTE':'Prib.Tekh.Eksp.',
    'PrPNP':'Prog.Part.Nucl.Phys.',
    'PSci':'Pour La Science',
    'PSSBR':'Phys.Status Solidi::B',
    'PSSCR':'Phys.Status Solidi::C',
    'PThPh':'Prog.Theor.Phys.',
    'PThPS':'Prog.Theor.Phys.Suppl.',
    'QApMa':'Q.Appl.Math.',
    'QJMAM':'Q.J.Mech.Appl.Math.',
    'QJRAS':'Q.J.Roy.Astron.Soc.',
    'Quest':'Rev.Quest.Sci.',
    'QuSOp':'Quant.Semiclass.Opt.',
    'R&QE':'Radiophys.Quant.Electron.',
    'RaF':'Izv.Vuz.Radiofiz.',
    'RaPC':'Radiat.Phys.Chem.',
    'RaRe':'Rad.Res.',
    'RaRLJ':'J.Radio Res.Lab.',
    'RaSc':'Radio Sci.',
    'RCARv':'RCA Rev.',
    'Rech':'Recherche',
    'RMxAA':'Rev.Mex.Astron.Astrofis.',
    'RMxAC':'Rev.Mex.Astron.Astrof.Ser.Conf.',
    'RMxF':'Rev.Mex.Fis.',
    'RpMP':'Rept.Math.Phys.',
    'RPPh':'Rept.Prog.Phys.',
    'RScI':'Rev.Sci.Instrum.',
    'RSPSA':'Proc.Roy.Soc.Lond.::A',
    'RSPSB':'Proc.Roy.Soc.Lond.::B',
    'RSPTA':'Phil.Trans.Roy.Soc.Lond.::A',
    'RSPTB':'Phil.Trans.Roy.Soc.Lond.::B',
    'RvGSP':'Rev.Geophys.',
    'RvMA':'Rev.Mod.Astron.',
    'RvMaP':'Rev.Math.Phys.',
    'RvMP':'Rev.Mod.Phys.',
    'RvPA':'Rev.Phys.Appl.',
    'RvRP':'Rom.J.Phys.',
    'SAJPh':'South Afr.J.Phys.',
    'SAJSc':'South Afr.J.Sci.',
    'ScChG':'Sci.China Phys.Mech.Astron.',
    'Sci':'Science',
    'SciAm':'Sci.Am.',
    'SciDi':'Sci.Dimens.',
    'SciSn':'Sci.Sin.',
    'SeAc':'Sens.Actuators',
    'SerAJ':'Serb.Astron.J.',
    'SeST':'Semicond.Sci.Tech.',
    'ShWav':'Shock Waves(Germany)',
    'SigPr':'Signal Processing',
    'SJAM':'SIAM J.Appl.Math.',
    'SJCO':'SIAM J.Control Optim.',
    'SJMA':'SIAM J.Math.Anal.',
    'SJNA':'SIAM J.Numer.Anal.',
    'SoCe':'Solar Energy Mater.Solar Cells',
    'SoEn':'Solar Energ.',
    'SoPh':'Solar Phys.',
    'SpFl':'Spaceflight',
    'SPhD':'Sov.Phys.Dokl.',
    'SPIE':'Proc.SPIE Int.Soc.Opt.Eng.',
    'SRL':'Surf. Rev. Lett.',
    'SSCom':'Solid State Commun.',
    'SScT':'Speculations Sci.Tech.',
    'SSEle':'Solid State Electron.',
    'SSI':'Space Sci.Instrum.',
    'SSRv':'Space Sci.Rev.',
    'SSTec':'Solid State Technol.',
    'StAM':'Stud.Appl.Math.',
    'StaSc':'Statist.Sci.',      
    'StMet':'Stat.Meth.',
    'SuMi':'Superlattices Microstruct.',
    'SurSc':'Surf.Sci.',
    'SuScT':'Supercond.Sci.Technol.',
    'SvA':'Sov.Astron.',
    'SvJNP':'Sov.J.Nucl.Phys.',
    'SvJPP':'Sov.J.Plasma Phys.',
    'SvJQE':'Quant.Electron.',
    'SvPhU':'Sov.Phys.Usp.',
    'Tecto':'Tectonophys.',
    'Tell':'Tellus',
    'TePhL':'Sov.Tech.Phys.Lett.',
    'ThCFD':'Theor.Comput.Fluid Dyn.',
    'TJPh':'Turk.J.Phys.',
    'TSF':'Thin Solid Films',
    'UkFiZ':'Ukr.Fiz.Zh.(Russ.Ed.)',
    'UkMaZ':'Ukr.Mat.Zh.',
    'UltIm':'Ultrason. Imag.',
    'Ultmi':'Ultramicroscopy',
    'Ultra':'Ultrasonics',
    'UsFiN':'Usp.Fiz.Nauk',
    'VA':'Vistas Astron.',
    'WaMot':'Wave Motion',
    'WisBT':'Wiss.Ber.AEG Telefunken',
    'WRM':'Waves Random Media',
    'ZaMM':'Z.Angew.Math.Mech.',
    'ZaMP':'Z.Angew.Math.Phys.',
    'ZhPS':'Zh.Prikl.Spektrosk.',
    'ZhTFi':'Zh.Tekh.Fiz.',
    'ZNatA':'Z.Naturforsch., Teil A',
    'ZPhy':'Z.Phys.',
    'ZPhyA':'Z.Phys.::A',
    'ZPhyB':'Z.Phys.::B',
    'ZPhyC':'Z.Phys.::C',
    'ZPhyD':'Z.Phys.::D'

    }

