DIRECTORY = '/afs/cern.ch/project/inspire/TEST/hoc/'
#DIRECTORY = '/home/hoc/'
DOCUMENT = 'ADSmatches.xml'
DOCUMENT = DIRECTORY + DOCUMENT
OUTPUT_COUNTER_MAX = 20000000000000

CORE_JOURNALS = ('Adv.High Energy Phys.',
'Atom.Data Nucl.Data Tabl.',
'Class.Quant.Grav.',
'JCAP',
'JHEAp',
'JHEP',
'LHEP',
'Nucl.Data Sheets',
'Nucl.Part.Phys.Proc.',
'Nucl.Phys.',
'Nucl.Phys.Proc.Suppl.',
'Phys.Dark Univ.',
'Phys.Part.Nucl.Lett.',
'Phys.Rev.Accel.Beams',
'Prog.Part.Nucl.Phys.')

CORE_JOURNALS_DOI = ('10.1103/PhysRevC', '10.1103/PhysRevD',
'10.1103/PhysRevAccelBeams',
'10.1016/j.nuclphysb', '10.1016/j.physlettb',
'10.1007/JHEP', '10.1140/epjc',
'10.1155', #AHEP
'10.5506/APhysPolB',
'10.1088/1674-1137', #Chin.Phys.C
'10.1088/1475-7516', #JCAP
'10.1088/1748-0221', #JINST
'10.1093/ptep/ptz022')

"""The two dictionaries JOURNAL_DICT and BIBCODE_DICT
convert ADS journal names to INSPIRE journal names."""

TRICKY_JOURNALS = ['Int.J.Mod.Phys.', 'Mod.Phys.Lett.', 'J.Phys.',
                   'Nucl.Phys.Proc.Suppl.', 'Europhys.Lett.',
                   'Proc.SPIE Int.Soc.Opt.Eng.']

JOURNAL_DICT = {
    'Acta.':'Acta Astron.',
    'Adv.Space.':'Adv.Space Res.',
    'AIP.':'AIP Conf.Proc.',
    'Annales':'Annales Henri Poincare',
    'Annals':'Annals Phys.',
    'ASP.':'ASP Conf.Ser.',
    'ASSL':'Astrophys.Space Sci.Libr.',
    'Astron.Nachr.':'Astron.Nachr.',
    'Astroph.J.':'Astrophys.J.',
    'Astrophys.Space.':'Astrophys.Space Sci.',
    'Baltic.':'Baltic Astron.',
    'Comm.Math.Phys.':'Commun.Math.Phys.',
    'Commun.Nonlinear.':'Commun.Nonlinear Sci.Numer.Simul.',
    'Contrib.Astron.Obs.Skalnate.':'Contrib.Astron.Obs.Skalnate Pleso',
    'EAS.Pub.Ser.':'EAS Publ.Ser.',
    'ESA.':'ESA Spec.Publ.',
    'Geophys.Astrophys.Fluid.':'Geophys.Astrophys.Fluid Dynamics',
    'Gravitat.Cosmol.':'Grav.Cosmol.',
    'IAU.':'IAU Symp.',
    'J.Fluid.':'J.Fluid Mech.',
    'J.Nonlin.Mathematical':'J.Nonlin.Mathematical Phys.',
    'Lect.Notes.':'Lect.Notes Phys.',
    'Low.':'Low Temp.Phys.',
    'New.':'New J.Phys.',
    'Phys.Rev.L.':'Phys.Rev.Lett.',
    'Proc.SPIE.':'Proc.SPIE Int.Soc.Opt.Eng.',
    'Res.Astron.Astroph.':'Res.Astron.Astrophys.',
    'Sov.Phys.JETP.Lett.':'JETP Lett.',
}

BIBCODE_DICT = {
    'A&A':'Astron.Astrophys.',
    'A&ARv':'Astron.Astrophys.Rev.',
    'A&AS':'Astron.Astrophys.Suppl.Ser.',
    'A&AT':'Astron.Astrophys.Trans.',
    'A&G':'Astron.Geophys.',
    'AAONw':'Ang.Austral.Obs.Epping Newslett.',
    'AAS':'Amer.Astron.Soc.Meeting',
    'AcA':'Acta Astron.',
    'AcAau':'Acta Astronaut.',
    'AcApS':'Acta Astrophys.Sin.',
    'AcASn':'Acta Astron.Sin.',
    'AcC':'Acta Cosmologica',
    'AcEle':'Acta Electron.',
    'AcHPh':'Helv.Phys.Acta',
    'AcMec':'Acta Mech.',
    'AcMet':'Acta Metall.',
    'AcNum':'Acta Numer.',
    'AcO':'Acta Oecologica',
    'AcOpt':'Opt.Acta',
    'ACP':'Atmosph.Chem.Phys.',
    'AcPhA':'Acta Phys.Austriaca',
    'AcPhH':'Acta Phys.Hung.',
    'AcPP':'Acta Phys.Polon.',
    'AcPPA':'Acta Phys.Polon.::A',
    'AcPPB':'Acta Phys.Polon.::B',
    'AcPSl':'Acta Phys.Slov.',
    'AcPSn':'Acta Phys.Sin.',
    'AcRhe':'Rheologica Acta',
    'ACSJ':'J.Amer.Ceramic Soc.',
    'AcSpe':'Spectrochim.Acta A',
    'AdA&A':'Adv.Astron.Astrophys.',
    'AdApM':'Adv.Appl.Math.',
    'AdAst':'Adv.Astron.',
    'ADNDT':'Atom.Data Nucl.Data Tabl.',
    'AdPhy':'Adv.Phys.',
    'AdSpR':'Adv.Space Res.',
    'AEdRv':'Astron.Educ.Rev.',
    'AeJ':'J.Aeron.Sci.',
    'AExpr':'Astron.Express',
    'Afz':'Astrofiz.',
    'AIAAJ':'AIAA J.',
    'AIChE':'Aiche J.',
    'AIPC':'AIP Conf.Proc.',
    'AJ':'Astron.J.',
    'AJSE':'Arabian J.Sci.Eng.',
    'AmJPh':'Am.J.Phys.',
    'AmJS':'Am.J.Sci.',
    'AmMin':'Amer.Miner.',
    'AmSci':'Am.Sci.',
    'AN':'Astron.Nachr.',
    'AnaCh':'Anal.Chem.',
    'AnAp':'Annales Astrophys.',
    'AnApS':'Ann.Appl.Stat.',
    'AnGeo':'Ann.Geophys.',
    'AnHP':'Annales Henri Poincare',
    'AnIHP':'Ann.Inst.Henri Poincare Phys.Theor.',
    'AnIPS':'Annals Israel Phys.Soc.',
    'AnP':'Annalen Phys.',
    'AnPh':'Annales Phys.(France)',
    'AnPhy':'Annals Phys.',
    'AnRFM':'Ann.Rev.Fluid Mech.',
    'Ap':'Astrophysics',
    'Ap&SS':'Astrophys.Space Sci.',
    'ApEnM':'Appl.Envir.Microbiol.',
    'APh':'Astropart.Phys.',
    'ApJ':'Astrophys.J.',
    'ApJS':'Astrophys.J.Suppl.',
    'ApL':'Astrophys.Lett.',
    'ApL&C':'Astrophys.Lett.Commun.',
    'ApMaL':'Appl.Math.Lett.',
    'ApMaO':'Appl.Math.Optim.',
    'ApMM':'Appl.Math.Mech.',
    'ApMRv':'Appl.Mech.Rev.',
    'ApNM':'Appl.Numer.Math.',
    'ApNr':'Astrophys.Nor.',
    'ApOpt':'Appl.Opt.',
    'AppAn':'Appl.Anal.',
    'ApPhA':'Appl.Phys.::A',
    'ApPhB':'Appl.Phys.B, Lasers Opt.',
    'ApPhL':'Appl.Phys.Lett.',
    'ApPhy':'Appl.Phys.',
    'ApPPL':'Appl.Phys.B Photophys.Laser Chem.',
    'ApScR':'Appl.Sci.Res.',
    'ApSpe':'Appl.Spectrosc.',
    'ApSS':'Appl.Surf.Sci.',
    'ApSup':'IEEE Trans.Appl.Supercond.',
    'ArA':'Ark.Mat.Astron.Fys.',
    'ARA&A':'Ann.Rev.Astron.Astrophys.',
    'ArApM':'Arch.Appl.Mech.',
    'ARCMP':'Ann.Rev.Condensed Matter Phys.',
    'ARep':'Astron.Rep.',
    'AREPS':'Ann.Rev.Earth Planet.Sci.',
    'ARIST':'Ann.Rev.Info.Sci.Tech.',
    'ArM':'Ark.Mat.',
    'ARNPS':'Ann.Rev.Nucl.Part.Sci.',
    'ArRMA':'Arch.Ration.Mech.Anal.',
    'ASAJ':'J.Acoust.Soc.Am.',
    'AsBio':'Astrobiology',
    'ASL':'Adv.Sci.Lett.',
    'ASPC':'ASP Conf.Ser.',
    'ASSP':'Astrophys.Space Sci.Proc.',
    'AstBu':'Astrophys.Bull.',
    'AstL':'Astron.Lett.',
    'ATeL':"Astronmer's Telegram",
    'AtERv':'At.Energy Rev.',
    'ATJFE':'J.Fluids Eng.',
    'AtO':'Atmos. Ocean Opt.',
    'AuJPh':'Austral.J.Phys.',
    'AuMSJ':'J.Austral.Math.Soc.Ser.B',
    'Autom':'Automatica',
    'AZh':'Astron.Zh.',
    'BAAA':'Bol.A.A.Astron.',
    'BAAS':'Bull.Am.Astron.Soc.',
    'BaltA':'Baltic Astron.',
    'BASBr':'Bull.Astron.Soc.Braz.',
    'BASI':'Bull.Astron.Soc.India',
    'BlgAJ':'Bulg.Astron.J.',
    'BlJPh':'Bulg.J.Phys.',
    'BpJ':'Biophys.J.',
    'BRASP':'Bull.Russ.Acad.Sci.Phys.',
    'BrJPh':'Braz.J.Phys.',
    'BSAO':'Bull.Spec.Astrophys.Obs.N.Caucasus',
    'BSRSL':'Bull.Soc.Roy.Sci.Liege',
    'CAD':'Comput. Aided Geom. Des.',
    'CaJCh':'Can.J.Chem.',
    'CaJPh':'Can.J.Phys.',
    'CCoPh':'Commun.Comput.Phys.',
    'CEAB':'Cent.Euro.Astro.Bull.',
    'CEJPh':'Central Eur.J.Phys.',
    'CeMDA':'Celestial Mech.Dyn.Astron.',
    'CG':'Comput.Geosci.',
    'CGIP':'Comput.Vision Graphics Image Proc.',
    'ChA&A':'Chin.Astron.Astrophys.',
    'Chaos':'Chaos',
    'ChEnS':'Chem.Eng.Sci.',
    'ChGeo':'Chem. Geol.',
    'ChJAA':'Chin.J.Astron.Astrophys.',
    'ChJAS':'Chin.J.Astron.Astrophys.Suppl.',
    'ChJNP':'Chin.J.Nucl.Phys.',
    'ChJPh':'Chin.J.Phys.',
    'ChPhy':'Chin.Phys.',
    'ChPhB':'Chin.Phys.::B',
    'ChPhC':'Chin.Phys.::C',
    'ChPhL':'Chin.Phys.Lett.',
    'CJLTP':'Chin.J.Low Temp.Phys.',
    'CliPa':'Climate Past',
    'CliPD':'Climate Past Disc.',
    'CMAME':'Comput.Methods Appl.Mech.Eng.',
    'CMaPh':'Commun.Math.Phys.',
    'CMT':'Contin.Mech.Thermodyn.',
    'CMwA':'Comput.Math.Appl.',
    'CNSNS':'Commun.Nonlinear Sci.Numer.Simul.',
    'CoAst':'Commun.Asteros.',
    'CoFl':'Combust.Flame',
    'ComAp':'Comments Astrophys.',
    'ComMP':'Comments Mod.Phys.',
    'Comp':'Computer',
    'ComPh':'Comput.Phys.',
    'ConPh':'Contemp.Phys.',
    'CoPhC':'Comput.Phys.Commun.',
    'CoPP':'Comments Plasma Phys.Contr.Fusion',
    'CoSka':'Contrib.Astron.Obs.Skalnate Pleso',
    'CoTPh':'Commun.Theor.Phys.',
    'CP':'Chem.Phys.',
    'CPAM':'Commun.Pure Appl.Math.',
    'CPL':'Chem.Phys.Lett.',
    'CQGra':'Class.Quant.Grav.',
    'CRAS':'C.R.Acad.Sci.',
    'CRASB':'C.R.Acad.Sci.::B',
    'CRASP':'C.R.Acad.Sci.IV Phys.Astrophys.',
    'CRPhy':'Comptes Rendus Physique',
    'Cryo':'Cryogenics',
    'CryRp':'Cystallogr.Rep.',
    'CS&D':'Comput.Sci.Dis.',
    'CSci':'Curr.Sci.',
    'CSF':'Chaos Solitons Fractals',
    'CST':'Combust.Sci.Tech.',
    'CzJPh':'Czech.J.Phys.',
    'CzMJ':'Czech.Math.J.',
    'DatSJ':'Data Sci.J.',
    'Disc':'Discover',
    'DokPh':'Phys.Dokl.',
    'DynCo':'J.Guid.Control Dyn.',
    'E&PSL':'Earth Planet.Sci.Lett.',
    'EAS':'EAS Publ.Ser.',
    'EcSJ':'J.Electrochem.Soc.',
    'EJPh':'Eur.J.Phys.',
    'EJTP':'Electron.J.Theor.Phys.',
    'EL':'Europhys.Lett.',
    'Elek':'Radiotekh.Elektron.',
    'ElL':'Electron.Lett.',
    'ElP':'Electron.Power',
    'EM&P':'Earth Moon Planets',
    'Endvr':'Endeavour',
    'ENews':'Europhys.News',
    'EnST':'Environ.Sci.Tech.',
    'Entrp':'Entropy',
    'EP&S':'Earth Planets Space',
    'EPJA':'Eur.Phys.J.::A',
    'EPJAP':'Eur.Phys.J.Appl.Phys.',
    'EPJB':'Eur.Phys.J.::B',
    'EPJC':'Eur.Phys.J.::C',
    'EPJD':'Eur.Phys.J.::D',
    'EPJE':'Eur.Phys.J.::E',
    'EPJH':'Eur.Phys.J.::H',
    'EPJP':'Eur.Phys.J.Plus',
    'EPJST':'Eur.Phys.J.ST',
    'EPJWC':'EPJ Web Conf.',
    'ERL':'Environ.Res.Lett.',
    'ESAJ':'ESA J.',
    'ExA':'Exper.Astron.',
    'ExT':'Instrum.Exp.Tech.',
    'FAAp':'Funct.Anal.Appl.',
    'FaDi':'Faraday Discuss.Chem.Soc.',
    'FBS':'Few Body Syst.',
    'FCPh':'Fund.Cosmic Phys.',
    'Fiz':'Fizika',
    'FizA':'Fizika::A',
    'FizB':'Fizika::B',
    'FizMS':'Fiz.Mnogochast.Sistem',
    'FizTT':'Fiz.Tverd.Tela',
    'FlDy':'Fluid Dynamics',
    'FlDyR':'Fluid Dynamics Res.',
    'FlMSR':'Fluid Mech.Sov.Res.',
    'FoPh':'Found.Phys.',
    'ForPh':'Fortsch.Phys.',
    'Fract':'Fractals',
    'GApFD':'Geophys.Astrophys.Fluid Dynamics',
    'Ge&Ae':'Geomagn.Aeron.',
    'GeCoA':'Geochim.Cosmochim.Acta',
    'GeGe':'Stud.Geophys.Geod.',
    'GeoJ':'Geophys.J.(U.S.)',
    'GeoJI':'Geophys.J.Int.',
    'GeoRL':'Geophys.Res.Lett.',
    'GGG':'Geochem.Geophys.Geosyst.',
    'GrCo':'Grav.Cosmol.',
    'GReGr':'Gen.Rel.Grav.',
    'HDP':'Handb.Phys.',
    'HeaPh':'Health Phys.',
    'HEDP':'High Energy Dens.Phys.',
    'HiA':'Highlights Astron.',
    'HMT':'Int.J.Heat Mass Transf.',
    'HTHP':'High Temp.High Pressures',
    'HyInt':'Hyperfine Interact.',
    'IAPM':'IEEE Anten.Propag.Mag.',
    'IAUC':'IAU Circ.',
    'IAUS':'IAU Symp.',
    'IBVS':'Inform.Bull.Var.Stars',
    'Icar':'Icarus',
    'ICML':'Int.Conf.Machine Learning',
    'IComM':'IEEE Commun.Mag.',
    'ICRC':'ICRC',
    'ICSE':'Impact Comput.Sci.Eng.',
    'IDAQP':'Inf.Dim.Anal.Quant.Probab.Rel.Top.',
    'IER':'Int.Elek.Rundsch.',
    'IEEEP':'IEEE Proc.',
    'IJAsB':'Int.J.Astrobiol.',
    'IJBC':'Int.J.Bifurc.Chaos',
    'IJC':'Int.J.Control',
    'IJE':'Int.J.Electron.',
    'IJES':'Int.J.Eng.Sci.',
    'IJGMM':'Int.J.Geom.Meth.Mod.Phys.',
    'IJIMW':'Int.J.Infrared MM Waves',
    'IJMPA':'Int.J.Mod.Phys.::A',
    'IJMPB':'Int.J.Mod.Phys.::B',
    'IJMPC':'Int.J.Mod.Phys.::C',
    'IJMPD':'Int.J.Mod.Phys.::D',
    'IJMPE':'Int.J.Mod.Phys.::E',
    'IJMPS':'Int.J.Mod.Phys.Conf.Ser.',
    'IJMSI':'Int.J.Mass Spectr.Ion Process.',
    'IJMSp':'Int.J.Mass Spectrometry',
    'IJN':'Int.J.Nanosci.',
    'IJNA':'IMA J.Numer.Anal.',
    'IJNME':'Int.J.Numer.Meth.Eng.',
    'IJNMF':'Int. J. Numer. Methods Fluids',
    'IJPAM':'Indian J.Pure Appl.Math.',
    'IJPAP':'Indian J.Pure Appl.Phys.',
    'IJQC':'Int.J.Quant.Chem.',
    'IJQE':'IEEE J.Quant.Electron.',
    'IJRA':'IEEE J.Robot.Automat.',
    'IJScA':'Int.J.Supercomput.Appl.',
    'IJSSC':'IEEE J.Solid State Circuits',
    'IJTP':'Int.J.Theor.Phys.',
    'InCh':'Inorg.Chem.',
    'InfCo':'Info.Control',
    'InfPh':'Infrared Physics',
    'InJPh':'Indian J.Phys.',
    'InJPA':'Indian J.Phys.::A',
    'InJPB':'Indian J.Phys.::B',
    'InJTP':'Indian J.Theor.Phys.',
    'InMat':'Invent.Math.',
    'InPhT':'Infrared Phys.Tech.',
    'InvPr':'Inverse Prob.',
    'IPTL':'IEEE Photonics Tech.Lett.',
    'IrAJ':'Irish Astron.J.',
    'ISPL':'IEEE Signal Process.Lett.',
    'ISPM':'IEEE Sig.Proc.Mag.',
    'IST':'Issues Sci.Technol.',
    'ISTSP':'IEEE J.Sel.Top.Sig.Proc.',
    'ITAC':'IEEE Trans.Automatic Control',
    'ITAP':'IEEE Trans.Anten.Propag.',
    'ITAS':'IEEE Trans.Appl.Supercond.',
    'ITASS':'IEEE Trans.Acoust.Speech Signal Proc.',
    'ITBE':'IEEE Trans.Biomed.Eng.',
    'ITCmp':'IEEE Trans.Comput.',
    'ITCom':'IEEE Trans.Commun.',
    'ITCS':'IEEE Trans.Circuits Theor.',
    'ITEdu':'IEEE Trans.Educ.',
    'ITEI':'IEEE Trans.Electric.Insul.',
    'ITElC':'IEEE Trans.Electromagn.Compat.',
    'ITGRS':'IEEE Trans.Geosci.Remote Sensing',
    'ITIA':'IEEE Trans.Indust.Appl.',
    'ITIM':'IEEE Trans.Instrum.Measur.',
    'ITIP':'IEEE Trans.Image Process.',
    'ITIT':'IEEE Trans.Info.Theor.',
    'ITM':'IEEE Trans.Magnetics',
    'ITMTT':'IEEE Trans.Microwave Theor.Tech.',
    'ITNN':'IEEE Trans.Neural Networks',
    'ITNS':'IEEE Trans.Nucl.Sci.',
    'ITPAM':'IEEE Trans.Pattern Anal.Machine Intell.',
    'ITPS':'IEEE Trans.Plasma Sci.',
    'ITRA':'IEEE Trans.Robotics Automation',
    'ITSE':'IEEE Trans.Software Eng.',
    'ITSMC':'IEEE Trans.Syst.Man Cybern.',
    'ITSP':'IEEE Trans.Signal Process.',
    'ITUFF':'IEEE Trans.Ultrason.Ferroelectr.Freq.Control',
    'IzMat':'Izv.Math.',
    'JAChS':'J.Am.Chem.Soc.',
    'JAD':'J.Astron.Data',
    'JAerS':'J.Aerosol Sci.',
    'JAG':'J.Appl.Geophys.',
    'JAHH':'J.Astron.Hist.Herit.',
    'JaJAP':'Jap.J.Appl.Phys.',
    'JAllC':'J.Alloys Compounds',
    'JAMS':'J.Am.Math.Soc.',
    'JAnSc':'J.Astronaut.Sci.',
    'JAP':'J.Appl.Phys.',
    'JApA':'J.Astrophys.Astron.',
    'JAPh':'J.Appl.Physiol.',
    'JApMa':'Ima J.Appl.Math.',
    'JApMe':'J.Appl.Meteor.',
    'JASS':'J.Astron.Space Sci.',
    'JASTP':'J.Atmos.Sol.Terr.Phys.',
    'JAtC':'J.Atmos.Chem.',
    'JATP':'J.Atmos.Terr.Phys.',
    'JAtS':'J.Atmos.Sci.',
    'JAVSO':'J.Am.Assoc.Var.Star Obs.',
    'JBAA':'J.Br.Astron.Assoc.',
    'JBIS':'J.Br.Interplanet.Soc.',
    'JCAP':'JCAP',
    'JCh':'J.Chromatogr.',
    'JChPh':'J.Chem.Phys.',
    'JCIS':'J.Coll.Interface Sci.',
    'JCM':'J.Comput.Appl.Math.',
    'JCoCh':'J.Comput.Chem.',
    'JCoPh':'J.Comput.Phys.',
    'JCos':'J.Cosmol.',
    'JCrGr':'J.Cryst.Growth',
    'JDE':'J.Diff.Eq.',
    'JDSO':'JDSO',
    'JEEEA':'J.Electr.Electron.Eng.Aust.',
    'JEMat':'J.Electron.Mater.',
    'JESRP':'J.Electron Spectrosc.Rel.Phenom.',
    'JETP':'J.Exp.Theor.Phys.',
    'JETPL':'JETP Lett.',
    'JEWA':'J.Electromagn.Waves Appl.',
    'JFAA':'J.Fourier Anal.Appl.',
    'JFM':'J.Fluid Mech.',
    'JG':'J.Geology',
    'JGE':'J.Geophys.Eng.',
    'JGeod':'J.Geod.',
    'JGG':'J.Geomag.Geoelectr.Japan',
    'JGla':'J.Glaciol.',
    'JGP':'J.Geom.Phys.',
    'JGR':'J.Geophys.Res.',
    'JGRA':'J.Geophys.Res.::A',
    'JGRD':'J.Geophys.Res.Atmos.',
    'JGRE':'J.Geophys.Res.Planets',
    'JHA':'J.Hist.Astron.',
    'JHEP':'JHEP',
    'JHyd':'J.Hydronaut.',
    'JIEq':'J.Integ.Eq.',
    'JIMIA':'J.Inst.Math.Appl.',
    'JIMO':'WGN',
    'JInst':'JINST',
    'JKAS':'J.Korean Astron.Soc.',
    'JKPS':'J.Korean Phys.Soc.',
    'JLCM':'J.Less Common Met.',
    'JLTP':'J.Low.Temp.Phys.',
    'JLwT':'J.Lightwave Tech.',
    'JMAA':'J.Math.Anal.Appl.',
    'JMagR':'J.Magn.Resonance',
    'JMatR':'J.Mater.Res.',
    'JMatS':'J.Materials Sci.Lett.',
    'JMec':'J.Mecan.',
    'JMecA':'J.Meca.Theor.Appl.',
    'JMemS':'J.Microelectromech.Syst.',
    'JMet':'J.Metals',
    'JMiMi':'J.Micromech.Microeng',
    'JMMM':'J.Magn.Magn.Mater.',
    'JMoEl':'J.Molec.Electron.',
    'JMolE':'J.Molec.Evol.',
    'JMOp':'J.Mod.Opt.',
    'JMoSp':'J.Molec.Spectrosc.',
    'JMoSt':'J.Molec.Struc.',
    'JMP':'J.Math.Phys.',
    'JMPh':'J.Mod.Phys.',
    'JMPSo':'J.Mech.Phys.Solids',
    'JNano':'J.Nanophoton.',
    'JNCS':'J.Noncryst.Solids',
    'JNET':'J.Nonequil.Thermo.',
    'JNMP':'J.Nonlin.Mathematical Phys.',
    'JNOPM':'J.Nonlin.Opt.Phys.Mater.',
    'JNS':'J.Nonlin.Sci.',
    'JNuM':'J.Nucl.Mater.',
    'JOpt':'J.Optics',
    'JOptA':'J.Opt.',
    'JOptB':'J.Opt.B Quant.Semiclass.Opt.',
    'JOSAA':'J.Opt.Soc.Am.::A',
    'JOSAB':'J.Opt.Soc.Am.::B',
    'JOTA':'J.Optim.Th.Appl.',
    'JPCA':'J.Phys.Chem.::A',
    'JPCM':'J.Phys.Condens.Matter',
    'JPCRD':'J.Phys.Chem.Ref.Data',
    'JPCS':'J.Phys.Chem.Solids',
    'JPDC':'J.Parallel Distrib.Comput.',
    'JPhA':'J.Phys.::A',
    'JPhB':'J.Phys.::B',
    'JPhC':'J.Phys.::C',
    'JPhCh':'J.Phys.Chem.',
    'JPhCS':'J.Phys.Conf.Ser.',
    'JPhD':'J.Phys.::D',
    'JPhE':'J.Phys.::E',
    'JPhF':'J.Phys.::F',
    'JPhG':'J.Phys.::G',
    'JPhSt':'J.Phys.Stud.',
    'JPhys':'J.Phys.(France)',
    'JPlPh':'J.Plasma Phys.',
    'JPO':'J.Phys.Oceanogr.',
    'JPP':'J.Propulsion Power',
    'JPSJ':'J.Phys.Soc.Jap.',
    'JPSJS':'J.Phys.Soc.Jap.Suppl.',
    'JQSRT':'J.Quant.Spectrosc.Radiat.Trans.',
    'JRAC':'J.Radioanal.Chem.',
    'JRASC':'J.Roy.Astron.Soc.Canada',
    'JRNBS':'J.Res.Natl.Bur.Stand.',
    'JSCom':'J.Sci.Comput.',
    'JSEdT':'J.Sci.Educ.Tech.',
    'JSeis':'J.Seismol.',
    'JSLR':'J.Russ.Laser Res.',
    'JSMTE':'J.Stat.Mech.',
    'JSP':'J.Statist.Phys.',
    'JSup':'J.Supercond.',
    'JSV':'J.Sound Vibrat.',
    'JTurb':'J.Turbulence',
    'JVST':'J.Vac.Sci.Tech.',
    'JVSTB':'J.Vac.Sci.Tech.::B',
    'JWasA':'J.Wash.Acad.Sci.',
    'KFNT':'Kinematika Fiz.Nebesnykh Tel',
    'KosNT':'Kosmichna Nauka Tekhnol.',
    'KPCB':'Kinematics Phys.Celest.Bodies',
    'LanB':'Landolt-Bornstein',
    'LaPhy':'Laser Phys.',
    'LaPhL':'Laser Phys.Lett.',
    'LicOB':'Lick Obs.Bull.',
    'LiCr':'Mol.Cryst.Liq.Cryst.',
    'LitJP':'Lith.J.Phys.Tech.Sci.',
    'LMaPh':'Lett.Math.Phys.',
    'LNCS':'Lect.Notes Comput.Sci.',
    'LNEA':'Lec.Note.Essays Astrophys.',
    'LNP':'Lect.Notes Phys.',
    'LPB':'Laser Part.Beams',
    'LRR':'Living Rev.Rel.',
    'LRSP':'Living Rev.Sol.Phys.',
    'LTP':'Low Temp.Phys.',
    'M&P':'Moon Planets',
    'M&PS':'Meteorit.Planet.Sci.',
    'MaCom':'Math.Comput.',
    'Math':'Mathematika',
    'MatL':'Mater.Lett.',
    'MComM':'Math.Comput.Modelling',
    'Mecc':'Meccanica',
    'MedPh':'Med.Phys.',
    'MeReC':'Mech.Res.Commun.',
    'MeScR':'Measur.Sci.Rev.',
    'MeScT':'Measur.Sci.Tech.',
    'Metic':'Meteoritics',
    'Metro':'Metrologia',
    'MiOTL':'Microw.Opt.Technol.Lett.',
    'MmARB':'Acad.Roy.Belg.Sci.Mem.',
    'MMAS':'Math.Methods Appl.Sci.',
    'MmRAS':'Mem.Roy.Astron.Soc.',
    'MmSAI':'Mem.Soc.Ast.It.',
    'MNRAS':'Mon.Not.Roy.Astron.Soc.',
    'MolPh':'Mol.Phys.',
    'ModPh':'Mod.Phys.',
    'MPCPS':'Math.Proc.Cambridge Phil.Soc.',
    'MPLA':'Mod.Phys.Lett.::A',
    'MPLB':'Mod.Phys.Lett.::B',
    'MSAIS':'Mem.Soc.Astron.Ital.Suppl.',
    'MSEng':'Mater.Sci.Eng.',
    'Msngr':'Messenger',
    'MSRSL':'Mem.Soc.Roy.Sci.Liege',
    'MUPB':'Moscow Univ.Phys.Bull.',
    'MWRv':'Mon.Weather Rev.',
    'NanoL':'Nano Lett.',
    'NRL':'Nanoscale Res.Lett.',
    'Nanot':'Nanotechnol.',
    'NaPho':'Nature Photon.',
    'Natur':'Nature',
    'NatCo':'Nature Commun.',
    'NatGe':'Nature Geo.',
    'NatMa':'Nature Materials',
    'NatNa':'Nature Nanotech.',
    'NatPh':'Nature Phys.',
    'NCimA':'Nuovo Cim.::A',
    'NCimB':'Nuovo Cim.::B',
    'NCimC':'Nuovo Cim.::C',
    'NCimD':'Nuovo Cim.::D',
    'NCimL':'Lett.Nuovo Cim.',
    'NCimR':'Riv.Nuovo Cim.',
    'NDS':'Nucl.Data Sheets',
    'NewA':'New Astron.',
    'NewAR':'New Astron.Rev.',
    'NewSc':'New Sci.',
    'NIMPA':'Nucl.Instrum.Meth.::A',
    'NIMPB':'Nucl.Instrum.Meth.::B',
    'NIMPR':'Nucl.Instrum.Meth.',
    'NInfo':'Nauchnye Inform.Astron.Sov.Akad Nauk SSR',
    'NISTJ':'J.Res.Natl.Inst.Stand.Tech.',
    'NJPh':'New J.Phys.',
    'Nonli':'Nonlinearity',
    'NPGeo':'Nonlin.Proc.Geophys.',
    'NPhS':'Nature Phys.Sci.',
    'NucFu':'Nucl.Fusion',
    'NucIM':'Nucl.Instrum.Meth.',
    'NucPh':'Nucl.Phys.',
    'NuMat':'Numer.Math.',
    'NuPh':'Nucl.Phys.',
    'NuPhA':'Nucl.Phys.::A',
    'NuPhB':'Nucl.Phys.::B',
    'NuPhS':'Nucl.Phys.Proc.Suppl.',
    'NW':'Naturwiss.',
    'NYASA':'Annals N.Y.Acad.Sci.',
    'OAP':'Odessa Astron.Pub.',
    'OAJ':'Open Astron.J.',
    'Obs':'Observatory',
    'OEJV':'Open Eur.J.Var.Stars',
    'OExpr':'Opt.Express',
    'OLEB':'Orig.Life.Evol.Biosph.',
    'ONCP':'Concepts Phys.',
    'ONPPJ':'Open Nucl.Part.Phys.J.',
    'OptCo':'Opt.Commun.',
    'OptEn':'Opt.Eng.',
    'OptL':'Opt.Lett.',
    'OptLT':'Opt.Laser Tech.',
    'OptMa':'Opt.Mater.',
    'OptN':'Optics News',
    'OptPN':'Opt.Phontonics News',
    'OptQE':'Opt.Quant.Electron.',
    'OptRv':'Opt.Rev.',
    'OptSp':'Opt.Spectrosc.',
    'OSAJ':'J.Opt.Soc.Am.',
    'P&SS':'Planet.Space Sci.',
    'PADEU':'Publ.Astron.Dep.Eotvos Univ.',
    'PAN':'Phys.Atom.Nucl.',
    'PApGe':'Pur.Appl.Geophys.',
    'ParC':'Parallel Comput.',
    'PaReL':'Pattern Recog.Lett.',
    'PASA':'Publ.Astron.Soc.Austral.',
    'PASAu':'Proc.Astron.Soc.Austral.',
    'PASJ':'Publ.Astron.Soc.Jap.',
    'PASP':'Publ.Astron.Soc.Pac.',
    'PCCP':'Phys.Chem.Chem.Phys.',
    'PDO':'Publ.Dominion Astrophys.Obs.',
    'PEPI':'Phys.Earth Planet.Interiors',
    'PFR':'Plasma Fusion Res.',
    'PhB':'Phys.Bull.',
    'PhFl':'Phys.Fluids',
    'PhL':'Phys.Lett.',
    'PhLA':'Phys.Lett.::A',
    'PhLB':'Phys.Lett.::B',
    'PhLC':'Phys.Rept.',
    'PhoSp':'Photonics Spectra',
    'PhP':'Phys.Perspect.',
    'PhPl':'Phys.Plasmas',
    'PhR':'Phys.Rept.',
    'PhRv':'Phys.Rev.',
    'PhRvA':'Phys.Rev.::A',
    'PhRvB':'Phys.Rev.::B',
    'PhRvC':'Phys.Rev.::C',
    'PhRvD':'Phys.Rev.::D',
    'PhRvE':'Phys.Rev.::E',
    'PhRvL':'Phys.Rev.Lett.',
    'PhRvS':'Phys.Rev.ST Accel.Beams',
    'PhT':'Phys.Today',
    'PhTea':'Phys.Teacher',
    'Phy':'Physica',
    'PhyA':'Physica::A',
    'PhyB':'Physica::B',
    'PhyC':'Physica::C',
    'PhyD':'Physica::D',
    'PhyE':'Physica::E',
    'PhyEd':'Phys.Educ.India',
    'PhyEs':'Phys.Essays',
    'PhST':'Phys.Scripta::T',
    'PhyS':'Phys.Scripta',
    'PhyU':'Phys.Usp.',
    'PJAB':'Proc.Japan Acad.::B',
    'PLoSO':'PLoS One',
    'PlPh':'Plasma Phys.',
    'PlPhR':'Plasma Phys.Rep.',
    'PLSCB':'PLoS Comp.Bio.',
    'PMag':'Phil.Mag.',
    'PMagA':'Phil.Mag.::A',
    'PMagB':'Phil.Mag.::B',
    'PMagL':'Phil.Mag.Lett.',
    'PMB':'Phys.Med.Biol.',
    'PNAS':'Proc.Nat.Acad.Sci.',
    'POBeo':'Publ.Obs.Astron.Beograd',
    'PPCF':'Comments Plasma Phys.Contr.Fusion',
    'PPN':'Phys.Part.Nucl.',
    'PPNL':'Phys.Part.Nucl.Lett.',
    'PQE':'Prog.Quant.Electron.',
    'Prama':'Pramana',
    'PrECS':'Prog.Energy Combust.Sci.',
    'PreR':'Precambrian Res.',
    'PRI':'Phys.Res.Int.',
    'PriTE':'Prib.Tekh.Eksp.',
    'PrPNP':'Prog.Part.Nucl.Phys.',
    'PSci':'Pour La Science',
    'PSSAR':'Phys.Status Solidi::A',
    'PSSBR':'Phys.Status Solidi::B',
    'PSSCR':'Phys.Status Solidi::C',
    'PSSRR':'Phys.Status Solidi RRL',
    'PSST':'Plasma Sources Sci.Tech.',
    'PThPh':'Prog.Theor.Phys.',
    'PThPS':'Prog.Theor.Phys.Suppl.',
    'PZ':'Peremeenya Zvezdy',
    'PZP':'Peremennye Zvezdy Prilozh.',
    'QApMa':'Q.Appl.Math.',
    'QJMAM':'Q.J.Mech.Appl.Math.',
    'QJRAS':'Q.J.Roy.Astron.Soc.',
    'Quest':'Rev.Quest.Sci.',
    'QuSOp':'Quant.Semiclass.Opt.',
    'R&QE':'Radiophys.Quant.Electron.',
    'RAA':'Res.Astron.Astrophys.',
    'RaF':'Izv.Vuz.Radiofiz.',
    'RaPC':'Radiat.Phys.Chem.',
    'RaRe':'Rad.Res.',
    'RaRLJ':'J.Radio Res.Lab.',
    'RaSc':'Radio Sci.',
    'RCARv':'RCA Rev.',
    'RCD':'Regular Chaot. Dyn.',
    'Rech':'Recherche',
    'RJMP':'Russ.J.Math.Phys.',
    'RLP':'Res.Lett.Phys.',
    'RMxAA':'Rev.Mex.Astron.Astrofis.',
    'RMxAC':'Rev.Mex.Astron.Astrof.Ser.Conf.',
    'RMxF':'Rev.Mex.Fis.',
    'RMxFE':'Rev.Mex.Fis.::E',
    'RMxFS':'Rev.Mex.Fis.Suppl.',
    'RoAJ':'Rom.Astron.J.',
    'RpMP':'Rept.Math.Phys.',
    'RPPh':'Rept.Prog.Phys.',
    'RScI':'Rev.Sci.Instrum.',
    'RSPSA':'Proc.Roy.Soc.Lond.::A',
    'RSPSB':'Proc.Roy.Soc.Lond.::B',
    'RSPTA':'Phil.Trans.Roy.Soc.Lond.::A',
    'RSPTB':'Phil.Trans.Roy.Soc.Lond.::B',
    'RuPhJ':'Russ.Phys.J.',
    'RvGSP':'Rev.Geophys.',
    'RvMA':'Rev.Mod.Astron.',
    'RvMaP':'Rev.Math.Phys.',
    'RvMP':'Rev.Mod.Phys.',
    'RvPA':'Rev.Phys.Appl.',
    'RvRP':'Rom.J.Phys.',
    'SAJPh':'South Afr.J.Phys.',
    'SAJSc':'South Afr.J.Sci.',
    'SASS':'Soc.Astron.Sci.Ann.Symp.',
    'ScChA':'Sci.China::A',
    'ScChG':'Sci.China Phys.Mech.Astron.',
    'Sci':'Science',
    'SciAm':'Sci.Am.',
    'SciDi':'Sci.Dimens.',
    'SciSn':'Sci.Sin.',
    'SeAc':'Sens.Actuators',
    'SerAJ':'Serb.Astron.J.',
    'SeST':'Semicond.Sci.Tech.',
    'SGeo':'Surveys in Geophys.',
    'ShWav':'Shock Waves(Germany)',
    'SigPr':'Signal Processing',
    'SJAM':'SIAM J.Appl.Math.',
    'SJCO':'SIAM J.Control Optim.',
    'SJMA':'SIAM J.Math.Anal.',
    'SJNA':'SIAM J.Numer.Anal.',
    'SMaS':'Smart Mater.Struct.',
    'SoCe':'Solar Energy Mater.Solar Cells',
    'SoEn':'Solar Energ.',
    'SoPh':'Solar Phys.',
    'SoSyR':'Sol.Syst.Res.',
    'SpFl':'Spaceflight',
    'SPhD':'Sov.Phys.Dokl.',
    'SPIE':'Proc.SPIE Int.Soc.Opt.Eng.',
    'SpWea':'Space Weather',
    'SRL':'Surf. Rev. Lett.',
    'SSCom':'Solid State Commun.',
    'SScT':'Speculations Sci.Tech.',
    'SSEle':'Solid State Electron.',
    'SSI':'Space Sci.Instrum.',
    'SSRv':'Space Sci.Rev.',
    'SSTec':'Solid State Technol.',
    'StAM':'Stud.Appl.Math.',
    'StaSc':'Statist.Sci.',
    'StMet':'Stat.Meth.',
    'SuMi':'Superlattices Microstruct.',
    'SunGe':'Sun Geosphere',
    'SurSc':'Surf.Sci.',
    'SuScT':'Supercond.Sci.Technol.',
    'SvA':'Sov.Astron.',
    'SvJNP':'Sov.J.Nucl.Phys.',
    'SvJPP':'Sov.J.Plasma Phys.',
    'SvJQE':'Quant.Electron.',
    'SvPhU':'Sov.Phys.Usp.',
    'Tecto':'Tectonophys.',
    'Tell':'Tellus',
    'TePhL':'Sov.Tech.Phys.Lett.',
    'ThCFD':'Theor.Comput.Fluid Dyn.',
    'TJPh':'Turk.J.Phys.',
    'TMP':'Theor.Math.Phys.',
    'TSF':'Thin Solid Films',
    'UkFiZ':'Ukr.Fiz.Zh.(Russ.Ed.)',
    'UkMaZ':'Ukr.Mat.Zh.',
    'UltIm':'Ultrason. Imag.',
    'Ultmi':'Ultramicroscopy',
    'Ultra':'Ultrasonics',
    'UsFiN':'Usp.Fiz.Nauk',
    'VA':'Vistas Astron.',
    'WaMot':'Wave Motion',
    'WisBT':'Wiss.Ber.AEG Telefunken',
    'WRM':'Waves Random Media',
    'ZaMM':'Z.Angew.Math.Mech.',
    'ZaMP':'Z.Angew.Math.Phys.',
    'ZhETF':'Zh.Eksp.Teor.Fiz.',
    'ZhPS':'Zh.Prikl.Spektrosk.',
    'ZhTFi':'Zh.Tekh.Fiz.',
    'ZNatA':'Z.Naturforsch., Teil A',
    'ZPhy':'Z.Phys.',
    'ZPhyA':'Z.Phys.::A',
    'ZPhyB':'Z.Phys.::B',
    'ZPhyC':'Z.Phys.::C',
    'ZPhyD':'Z.Phys.::D'
}


